version: "2.0"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_USERNAME: $BOT_USERNAME
      BOT_TOKEN: $BOT_TOKEN
      STRING_SESSION: $STRING_SESSION
      OWNER_ID: $OWNER_ID
